services:
  mamovies-form:
    build: .
    container_name: mamovies-form-upload
    ports:
      - "${PORT:-3333}:3333"
    environment:
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    restart: unless-stopped
    networks:
      - mamovies-network

networks:
  mamovies-network:
    external: true
